version: '3'
services:
  app:
    build: flask
    volumes:
      -python_ats:python_ats:rw
    ports:
      -"8080:5000"

    proxy:
      build: nginx
      restart: always
      ports:
        - 80:80
      depends_on:
        app
  volumes:
    app:    